name: upper-build

on:
    push:
        paths: 
            - ".github/workflows/upper-build.yml"
            - "upper/**"
    workflow_dispatch: # manual

jobs:
    # You can have multiple jobs and names
    build:
        runs-on: ubuntu-latest
        steps: 
            - run: pwd && ls -al
            # Specify a particular Go version...
            # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
            # https://github.com/actions/runner-images/blob/main/images/ubuntu/toolsets/toolset-2204.json
            - uses: "actions/checkout@v4"
            - run: pwd && ls -al
            - uses: "actions/setup-go@v5"
              with:
                # go-version: '1.22'
                go-version-file: ./upper/go.mod
                cache-dependency-path: ./upper/go.sum
            # https://github.com/marketplace/actions/setup-go-environment
            # https://github.com/marketplace
            - run: go mod download
            # Inline multi line script. Caution the indentation!
            - run: |
                ls
                go build
                ls
                go test
                ./upper foo the bar
              working-directory: upper